//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int SocialID { get; set; }
        public string SocialName { get; set; }
        public string SocialIcon { get; set; }
        public string SocialUrl { get; set; }
    }
}
